spring:
  application:
    name: order-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        healthCheckInterval: 15s
#  kafka:
#    producer:
#      value-serializer: com.ienliven.serializer.OrderSerializers
#      bootstrap-servers:
#        - localhost:9093
#        - localhost:9094

server:
  port: 8082
