spring:
  application:
    name: inventory
  cloud:
    consul:
      host: 172.20.20.10
      port: 8500
  kafka:
    consumer:
      bootstrap-servers:
        - localhost:9093
        - localhost:9094

server:
  port: 8081

