version: '2'

services:

  zookeeper:
    image: strimzi/kafka:0.20.0-kafka-2.6.0
    command: [
        "sh", "-c",
        "bin/zookeeper-server-start.sh config/zookeeper.properties"
    ]
    ports:
      - "2181:2181"
    environment:
      LOG_DIR: /tmp/logs

  kafka:
    image: strimzi/kafka:0.20.0-kafka-2.6.0
    command: [
        "sh", "-c",
        "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}",
        "bin/kafka-topics.sh --create --zookeeper $${KAFKA_ZOOKEEPER_CONNECT} --topic orders",
        "bin/kafka-topics.sh --list --zookeeper $${KAFKA_ZOOKEEPER_CONNECT}",
        "bin/kafka-topics.sh --create --zookeeper $${KAFKA_ZOOKEEPER_CONNECT} --topic payment-request",
        "bin/kafka-topics.sh --create --zookeeper $${KAFKA_ZOOKEEPER_CONNECT} --topic payment-status"
    ]
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181